# -*- coding: utf-8 -*-
"""Time series analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UZsPzKHtn2PK5ZCL9mvmJefoL3KqkZbH

# **📚 1. Import thư viện cần thiết**
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.tsa.stattools import adfuller
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf
from sklearn.metrics import mean_squared_error

# Cài đặt chung cho matplotlib và seaborn
sns.set_style("whitegrid")
plt.rcParams['figure.figsize'] = (12, 6)

"""# **📚 2. Đọc dữ liệu và xử lí dữ liệu**"""

# Đọc dữ liệu từ URL
DATA_PATH = "https://redcap.huph.edu.vn/ddp/tsa/nhom4.csv"
df = pd.read_csv(DATA_PATH, sep=',', decimal='.', na_values=-200)

# Chọn các cột cần thiết
cols = ['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
        'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)',
        'PT08.S4(NO2)', 'PT08.S5(O3)', 'T', 'RH', 'AH']
df = df[cols]

# Chuyển đổi sang datetime và đặt làm index
df['Timestamp'] = pd.to_datetime(df['Date'] + ' ' + df['Time'])
df = df.drop(columns=['Date', 'Time']).set_index('Timestamp')

# Xử lý giá trị thiếu
df = df.dropna()

# Hiển thị thông tin cơ bản
print("Shape:", df.shape)
print("\nInfo:")
print(df.info())
print("\n5 dòng đầu tiên:")
print(df.head())

"""# **📚 3. Plot dữ liệu thô**

# 3.1 Plot chất ô nhiễm
"""

plt.figure(figsize=(15, 10))
pollutants = ['CO(GT)', 'NMHC(GT)', 'C6H6(GT)', 'NOx(GT)', 'NO2(GT)']
for i, col in enumerate(pollutants, 1):
    plt.subplot(3, 2, i)
    plt.plot(df.index, df[col], linewidth=1)
    plt.title(col)
plt.tight_layout()
plt.show()

"""# 3.2 Plot thời tiết"""

plt.figure(figsize=(12, 8))
meteo = ['T', 'RH', 'AH']
for i, col in enumerate(meteo, 1):
    plt.subplot(3, 1, i)
    plt.plot(df.index, df[col], color='orange', linewidth=1)
    plt.title(col)
plt.tight_layout()
plt.show()

"""# 3.3 Plot sensor"""

plt.figure(figsize=(15, 10))
sensors = ['PT08.S1(CO)', 'PT08.S2(NMHC)', 'PT08.S3(NOx)', 'PT08.S4(NO2)', 'PT08.S5(O3)']
for i, col in enumerate(sensors, 1):
    plt.subplot(3, 2, i)
    plt.plot(df.index, df[col], color='green', linewidth=1)
    plt.title(col)
plt.tight_layout()
plt.show()

"""# **📚 4. Phân tích thành phần mùa vụ (Seasonal Decomposition)**"""

print("\n📚 4. Phân tích thành phần mùa vụ (Seasonal Decomposition):")
for col in df.columns:
    series = df[col].dropna()
    if len(series) >= 48:  # Đảm bảo đủ dữ liệu cho decomposition
        try:
            result = seasonal_decompose(series, model='additive', period=24)
            result.plot()
            plt.suptitle(f"Decomposition of {col}", y=1.02)
            plt.tight_layout()
            plt.show()
        except Exception as e:
            print(f"⚠ Không thể decomposition biến {col}: {e}")
    else:
        print(f"⚠ Biến {col} không đủ dữ liệu để decomposition (ít hơn 48 quan sát).")

"""# **📚 5. Kiểm tra tính dừng (ADF Test)**"""

print("\n📚 5. Kiểm tra tính dừng (ADF Test):")
for col in df.columns:
    series = df[col].dropna()
    if len(series) > 0:
        try:
            result = adfuller(series)
            print(f"\nVariable: {col}")
            print(f'ADF Statistic: {result[0]:.4f}')
            print(f'p-value: {result[1]:.4f}')
            print('Critical Values:')
            for key, value in result[4].items():
                print(f'   {key}: {value:.4f}')
            if result[1] > 0.05:
                print("=> Chuỗi không dừng (non-stationary)")
            else:
                print("=> Chuỗi dừng (stationary)")
        except Exception as e:
            print(f"⚠ Không thể kiểm tra ADF cho biến {col}: {e}")
    else:
        print(f"⚠ Biến {col} không có dữ liệu để kiểm tra ADF.")

"""# **📚 6. Vẽ ACF và PACF**"""

print("\n📚 6. Vẽ ACF và PACF:")
for col in df.columns:
    series = df[col].dropna()
    if len(series) >= 50:  # Đảm bảo đủ dữ liệu để vẽ ACF, PACF
        try:
            plt.figure(figsize=(12, 6))
            plt.suptitle(f"ACF and PACF for {col}", y=1.02)

            plt.subplot(1, 2, 1)
            plot_acf(series, ax=plt.gca(), lags=40)

            plt.subplot(1, 2, 2)
            plot_pacf(series, ax=plt.gca(), lags=40, method='ywmle')

            plt.tight_layout()
            plt.show()
        except Exception as e:
            print(f"⚠ Không thể vẽ ACF/PACF cho biến {col}: {e}")
    else:
        print(f"⚠ Biến {col} không đủ dữ liệu để vẽ ACF/PACF.")

"""# **📚 7. Moving Average (Trung bình trượt 24h)**"""

for col in df.columns:
    plt.figure(figsize=(12, 5))
    df[col].plot(label='Original', alpha=0.5)
    df[col].rolling(window=24).mean().plot(label='24h Rolling Mean', linewidth=2)
    plt.title(f"Original vs 24h Moving Average - {col}")
    plt.legend()
    plt.show()

"""# **📚 8. Exponential Moving Average (EMA)**"""

for col in df.columns:
    plt.figure(figsize=(12, 5))
    df[col].plot(label='Original', alpha=0.5)
    df[col].ewm(span=24).mean().plot(label='EMA (span=24)', linewidth=2, color='red')
    plt.title(f"Original vs EMA - {col}")
    plt.legend()
    plt.show()

"""# **📚 9. Forecast Evaluation (Naive RMSE)**"""

for col in df.columns:
    y_true = df[col][1:]
    y_pred = df[col][:-1]
    rmse = np.sqrt(mean_squared_error(y_true, y_pred))
    print(f"RMSE for {col}: {rmse:.4f}")